//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthConfig) DeepCopyInto(out *BasicAuthConfig) {
	*out = *in
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthConfig.
func (in *BasicAuthConfig) DeepCopy() *BasicAuthConfig {
	if in == nil {
		return nil
	}
	out := new(BasicAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CamelCaseTransformation) DeepCopyInto(out *CamelCaseTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CamelCaseTransformation.
func (in *CamelCaseTransformation) DeepCopy() *CamelCaseTransformation {
	if in == nil {
		return nil
	}
	out := new(CamelCaseTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CastTransformation) DeepCopyInto(out *CastTransformation) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CastTransformation.
func (in *CastTransformation) DeepCopy() *CastTransformation {
	if in == nil {
		return nil
	}
	out := new(CastTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSinkSpec) DeepCopyInto(out *ClickHouseSinkSpec) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.BatchFlushIntervalSeconds != nil {
		in, out := &in.BatchFlushIntervalSeconds, &out.BatchFlushIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.UpsertMode != nil {
		in, out := &in.UpsertMode, &out.UpsertMode
		*out = new(bool)
		**out = **in
	}
	if in.ConflictKey != nil {
		in, out := &in.ConflictKey, &out.ConflictKey
		*out = new(string)
		**out = **in
	}
	if in.TableEngine != nil {
		in, out := &in.TableEngine, &out.TableEngine
		*out = new(string)
		**out = **in
	}
	if in.ReplacingVersionColumn != nil {
		in, out := &in.ReplacingVersionColumn, &out.ReplacingVersionColumn
		*out = new(string)
		**out = **in
	}
	if in.RawMode != nil {
		in, out := &in.RawMode, &out.RawMode
		*out = new(bool)
		**out = **in
	}
	in.FlattenMetadataSpec.DeepCopyInto(&out.FlattenMetadataSpec)
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSinkSpec.
func (in *ClickHouseSinkSpec) DeepCopy() *ClickHouseSinkSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseSourceSpec) DeepCopyInto(out *ClickHouseSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(int32)
		**out = **in
	}
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ReadBatchSize != nil {
		in, out := &in.ReadBatchSize, &out.ReadBatchSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseSourceSpec.
func (in *ClickHouseSourceSpec) DeepCopy() *ClickHouseSourceSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlow) DeepCopyInto(out *DataFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlow.
func (in *DataFlow) DeepCopy() *DataFlow {
	if in == nil {
		return nil
	}
	out := new(DataFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowCronSpec.
func (in *DataFlowCronSpec) DeepCopy() *DataFlowCronSpec {
	if in == nil {
		return nil
	}
	out := new(DataFlowCronSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowCronStatus.
func (in *DataFlowCronStatus) DeepCopy() *DataFlowCronStatus {
	if in == nil {
		return nil
	}
	out := new(DataFlowCronStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowCronTrigger.
func (in *DataFlowCronTrigger) DeepCopy() *DataFlowCronTrigger {
	if in == nil {
		return nil
	}
	out := new(DataFlowCronTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowList) DeepCopyInto(out *DataFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowList.
func (in *DataFlowList) DeepCopy() *DataFlowList {
	if in == nil {
		return nil
	}
	out := new(DataFlowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowSpec) DeepCopyInto(out *DataFlowSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Sink.DeepCopyInto(&out.Sink)
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]TransformationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = new(ErrorSinkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.CheckpointPersistence != nil {
		in, out := &in.CheckpointPersistence, &out.CheckpointPersistence
		*out = new(bool)
		**out = **in
	}
	if in.CheckpointSyncOnAck != nil {
		in, out := &in.CheckpointSyncOnAck, &out.CheckpointSyncOnAck
		*out = new(bool)
		**out = **in
	}
	if in.CheckpointSaveInterval != nil {
		in, out := &in.CheckpointSaveInterval, &out.CheckpointSaveInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CheckpointReset != nil {
		in, out := &in.CheckpointReset, &out.CheckpointReset
		*out = new(bool)
		**out = **in
	}
	if in.StrictIdempotency != nil {
		in, out := &in.StrictIdempotency, &out.StrictIdempotency
		*out = new(bool)
		**out = **in
	}
	if in.ChannelBufferSize != nil {
		in, out := &in.ChannelBufferSize, &out.ChannelBufferSize
		*out = new(int32)
		**out = **in
	}
	if in.TransformWorkers != nil {
		in, out := &in.TransformWorkers, &out.TransformWorkers
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(MaintenanceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowSpec.
func (in *DataFlowSpec) DeepCopy() *DataFlowSpec {
	if in == nil {
		return nil
	}
	out := new(DataFlowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataFlowStatus) DeepCopyInto(out *DataFlowStatus) {
	*out = *in
	if in.LastProcessedTime != nil {
		in, out := &in.LastProcessedTime, &out.LastProcessedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaintenanceStatus != nil {
		in, out := &in.MaintenanceStatus, &out.MaintenanceStatus
		*out = new(MaintenanceStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataFlowStatus.
func (in *DataFlowStatus) DeepCopy() *DataFlowStatus {
	if in == nil {
		return nil
	}
	out := new(DataFlowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebeziumUnwrapTransformation) DeepCopyInto(out *DebeziumUnwrapTransformation) {
	*out = *in
	if in.AddSourceFields != nil {
		in, out := &in.AddSourceFields, &out.AddSourceFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebeziumUnwrapTransformation.
func (in *DebeziumUnwrapTransformation) DeepCopy() *DebeziumUnwrapTransformation {
	if in == nil {
		return nil
	}
	out := new(DebeziumUnwrapTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorSinkSpec) DeepCopyInto(out *ErrorSinkSpec) {
	*out = *in
	in.SinkSpec.DeepCopyInto(&out.SinkSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorSinkSpec.
func (in *ErrorSinkSpec) DeepCopy() *ErrorSinkSpec {
	if in == nil {
		return nil
	}
	out := new(ErrorSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtractFieldTransformation) DeepCopyInto(out *ExtractFieldTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtractFieldTransformation.
func (in *ExtractFieldTransformation) DeepCopy() *ExtractFieldTransformation {
	if in == nil {
		return nil
	}
	out := new(ExtractFieldTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterTransformation) DeepCopyInto(out *FilterTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterTransformation.
func (in *FilterTransformation) DeepCopy() *FilterTransformation {
	if in == nil {
		return nil
	}
	out := new(FilterTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlattenMetadataSpec) DeepCopyInto(out *FlattenMetadataSpec) {
	*out = *in
	if in.FlattenMetadataColumns != nil {
		in, out := &in.FlattenMetadataColumns, &out.FlattenMetadataColumns
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlattenMetadataSpec.
func (in *FlattenMetadataSpec) DeepCopy() *FlattenMetadataSpec {
	if in == nil {
		return nil
	}
	out := new(FlattenMetadataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlattenTransformation) DeepCopyInto(out *FlattenTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlattenTransformation.
func (in *FlattenTransformation) DeepCopy() *FlattenTransformation {
	if in == nil {
		return nil
	}
	out := new(FlattenTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadersToPayloadTransformation) DeepCopyInto(out *HeadersToPayloadTransformation) {
	*out = *in
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadersToPayloadTransformation.
func (in *HeadersToPayloadTransformation) DeepCopy() *HeadersToPayloadTransformation {
	if in == nil {
		return nil
	}
	out := new(HeadersToPayloadTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HoistFieldTransformation) DeepCopyInto(out *HoistFieldTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HoistFieldTransformation.
func (in *HoistFieldTransformation) DeepCopy() *HoistFieldTransformation {
	if in == nil {
		return nil
	}
	out := new(HoistFieldTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergSinkSpec) DeepCopyInto(out *IcebergSinkSpec) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.BatchFlushIntervalSeconds != nil {
		in, out := &in.BatchFlushIntervalSeconds, &out.BatchFlushIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.RawMode != nil {
		in, out := &in.RawMode, &out.RawMode
		*out = new(bool)
		**out = **in
	}
	in.FlattenMetadataSpec.DeepCopyInto(&out.FlattenMetadataSpec)
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogURISecretRef != nil {
		in, out := &in.CatalogURISecretRef, &out.CatalogURISecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OAuth2ServerURISecretRef != nil {
		in, out := &in.OAuth2ServerURISecretRef, &out.OAuth2ServerURISecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OAuth2ClientIDSecretRef != nil {
		in, out := &in.OAuth2ClientIDSecretRef, &out.OAuth2ClientIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OAuth2ClientSecretSecretRef != nil {
		in, out := &in.OAuth2ClientSecretSecretRef, &out.OAuth2ClientSecretSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AccessKeySecretRef != nil {
		in, out := &in.AccessKeySecretRef, &out.AccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SecretAccessKeySecretRef != nil {
		in, out := &in.SecretAccessKeySecretRef, &out.SecretAccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergSinkSpec.
func (in *IcebergSinkSpec) DeepCopy() *IcebergSinkSpec {
	if in == nil {
		return nil
	}
	out := new(IcebergSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergSourceSpec) DeepCopyInto(out *IcebergSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(int32)
		**out = **in
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogURISecretRef != nil {
		in, out := &in.CatalogURISecretRef, &out.CatalogURISecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OAuth2ServerURISecretRef != nil {
		in, out := &in.OAuth2ServerURISecretRef, &out.OAuth2ServerURISecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OAuth2ClientIDSecretRef != nil {
		in, out := &in.OAuth2ClientIDSecretRef, &out.OAuth2ClientIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.OAuth2ClientSecretSecretRef != nil {
		in, out := &in.OAuth2ClientSecretSecretRef, &out.OAuth2ClientSecretSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.IncrementalBySnapshot != nil {
		in, out := &in.IncrementalBySnapshot, &out.IncrementalBySnapshot
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotCheckpoints != nil {
		in, out := &in.SnapshotCheckpoints, &out.SnapshotCheckpoints
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergSourceSpec.
func (in *IcebergSourceSpec) DeepCopy() *IcebergSourceSpec {
	if in == nil {
		return nil
	}
	out := new(IcebergSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsertFieldTransformation) DeepCopyInto(out *InsertFieldTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsertFieldTransformation.
func (in *InsertFieldTransformation) DeepCopy() *InsertFieldTransformation {
	if in == nil {
		return nil
	}
	out := new(InsertFieldTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSinkSpec) DeepCopyInto(out *KafkaSinkSpec) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SASL != nil {
		in, out := &in.SASL, &out.SASL
		*out = new(SASLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BrokersSecretRef != nil {
		in, out := &in.BrokersSecretRef, &out.BrokersSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TopicSecretRef != nil {
		in, out := &in.TopicSecretRef, &out.TopicSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSinkSpec.
func (in *KafkaSinkSpec) DeepCopy() *KafkaSinkSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaSourceSpec) DeepCopyInto(out *KafkaSourceSpec) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SASL != nil {
		in, out := &in.SASL, &out.SASL
		*out = new(SASLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BrokersSecretRef != nil {
		in, out := &in.BrokersSecretRef, &out.BrokersSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TopicSecretRef != nil {
		in, out := &in.TopicSecretRef, &out.TopicSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ConsumerGroupSecretRef != nil {
		in, out := &in.ConsumerGroupSecretRef, &out.ConsumerGroupSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AvroSchemaSecretRef != nil {
		in, out := &in.AvroSchemaSecretRef, &out.AvroSchemaSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SchemaRegistry != nil {
		in, out := &in.SchemaRegistry, &out.SchemaRegistry
		*out = new(SchemaRegistryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsumerMaxWait != nil {
		in, out := &in.ConsumerMaxWait, &out.ConsumerMaxWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.FetchMinBytes != nil {
		in, out := &in.FetchMinBytes, &out.FetchMinBytes
		*out = new(int32)
		**out = **in
	}
	if in.FetchMaxBytes != nil {
		in, out := &in.FetchMaxBytes, &out.FetchMaxBytes
		*out = new(int32)
		**out = **in
	}
	if in.MaxPartitionFetchBytes != nil {
		in, out := &in.MaxPartitionFetchBytes, &out.MaxPartitionFetchBytes
		*out = new(int32)
		**out = **in
	}
	if in.NetReadTimeout != nil {
		in, out := &in.NetReadTimeout, &out.NetReadTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NetWriteTimeout != nil {
		in, out := &in.NetWriteTimeout, &out.NetWriteTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceSpec.
func (in *KafkaSourceSpec) DeepCopy() *KafkaSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakConfig) DeepCopyInto(out *KeycloakConfig) {
	*out = *in
	if in.ServerURLSecretRef != nil {
		in, out := &in.ServerURLSecretRef, &out.ServerURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.RealmSecretRef != nil {
		in, out := &in.RealmSecretRef, &out.RealmSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ClientIDSecretRef != nil {
		in, out := &in.ClientIDSecretRef, &out.ClientIDSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ClientSecretSecretRef != nil {
		in, out := &in.ClientSecretSecretRef, &out.ClientSecretSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakConfig.
func (in *KeycloakConfig) DeepCopy() *KeycloakConfig {
	if in == nil {
		return nil
	}
	out := new(KeycloakConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSpec) DeepCopyInto(out *MaintenanceSpec) {
	*out = *in
	if in.Suspended != nil {
		in, out := &in.Suspended, &out.Suspended
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceSpec.
func (in *MaintenanceSpec) DeepCopy() *MaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceStatus) DeepCopyInto(out *MaintenanceStatus) {
	*out = *in
	if in.NextMaintenanceTime != nil {
		in, out := &in.NextMaintenanceTime, &out.NextMaintenanceTime
		*out = (*in).DeepCopy()
	}
	if in.LastMaintenanceTime != nil {
		in, out := &in.LastMaintenanceTime, &out.LastMaintenanceTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceStatus.
func (in *MaintenanceStatus) DeepCopy() *MaintenanceStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaskTransformation) DeepCopyInto(out *MaskTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaskTransformation.
func (in *MaskTransformation) DeepCopy() *MaskTransformation {
	if in == nil {
		return nil
	}
	out := new(MaskTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NessieSinkSpec) DeepCopyInto(out *NessieSinkSpec) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.BatchFlushIntervalSeconds != nil {
		in, out := &in.BatchFlushIntervalSeconds, &out.BatchFlushIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.RawMode != nil {
		in, out := &in.RawMode, &out.RawMode
		*out = new(bool)
		**out = **in
	}
	in.FlattenMetadataSpec.DeepCopyInto(&out.FlattenMetadataSpec)
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseURLSecretRef != nil {
		in, out := &in.BaseURLSecretRef, &out.BaseURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.AccessKeySecretRef != nil {
		in, out := &in.AccessKeySecretRef, &out.AccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SecretAccessKeySecretRef != nil {
		in, out := &in.SecretAccessKeySecretRef, &out.SecretAccessKeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NessieSinkSpec.
func (in *NessieSinkSpec) DeepCopy() *NessieSinkSpec {
	if in == nil {
		return nil
	}
	out := new(NessieSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NessieSourceSpec) DeepCopyInto(out *NessieSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(int32)
		**out = **in
	}
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseURLSecretRef != nil {
		in, out := &in.BaseURLSecretRef, &out.BaseURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.NamespaceSecretRef != nil {
		in, out := &in.NamespaceSecretRef, &out.NamespaceSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.IncrementalBySnapshot != nil {
		in, out := &in.IncrementalBySnapshot, &out.IncrementalBySnapshot
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotCheckpoints != nil {
		in, out := &in.SnapshotCheckpoints, &out.SnapshotCheckpoints
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NessieSourceSpec.
func (in *NessieSourceSpec) DeepCopy() *NessieSourceSpec {
	if in == nil {
		return nil
	}
	out := new(NessieSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLCDCSourceSpec) DeepCopyInto(out *PostgreSQLCDCSourceSpec) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreateSlotIfNotExists != nil {
		in, out := &in.CreateSlotIfNotExists, &out.CreateSlotIfNotExists
		*out = new(bool)
		**out = **in
	}
	if in.CreatePublicationIfNotExists != nil {
		in, out := &in.CreatePublicationIfNotExists, &out.CreatePublicationIfNotExists
		*out = new(bool)
		**out = **in
	}
	if in.HeartbeatIntervalSeconds != nil {
		in, out := &in.HeartbeatIntervalSeconds, &out.HeartbeatIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.IncludeColumns != nil {
		in, out := &in.IncludeColumns, &out.IncludeColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeColumns != nil {
		in, out := &in.ExcludeColumns, &out.ExcludeColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SlotNameSecretRef != nil {
		in, out := &in.SlotNameSecretRef, &out.SlotNameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.PublicationNameSecretRef != nil {
		in, out := &in.PublicationNameSecretRef, &out.PublicationNameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLCDCSourceSpec.
func (in *PostgreSQLCDCSourceSpec) DeepCopy() *PostgreSQLCDCSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLCDCSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSinkSpec) DeepCopyInto(out *PostgreSQLSinkSpec) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.BatchFlushIntervalSeconds != nil {
		in, out := &in.BatchFlushIntervalSeconds, &out.BatchFlushIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.UpsertMode != nil {
		in, out := &in.UpsertMode, &out.UpsertMode
		*out = new(bool)
		**out = **in
	}
	if in.ConflictKey != nil {
		in, out := &in.ConflictKey, &out.ConflictKey
		*out = new(string)
		**out = **in
	}
	if in.UpsertVersionColumn != nil {
		in, out := &in.UpsertVersionColumn, &out.UpsertVersionColumn
		*out = new(string)
		**out = **in
	}
	if in.UpsertStrategy != nil {
		in, out := &in.UpsertStrategy, &out.UpsertStrategy
		*out = new(string)
		**out = **in
	}
	if in.SoftDeleteColumn != nil {
		in, out := &in.SoftDeleteColumn, &out.SoftDeleteColumn
		*out = new(string)
		**out = **in
	}
	if in.RawMode != nil {
		in, out := &in.RawMode, &out.RawMode
		*out = new(bool)
		**out = **in
	}
	in.FlattenMetadataSpec.DeepCopyInto(&out.FlattenMetadataSpec)
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSinkSpec.
func (in *PostgreSQLSinkSpec) DeepCopy() *PostgreSQLSinkSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLSourceSpec) DeepCopyInto(out *PostgreSQLSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(int32)
		**out = **in
	}
	if in.ConnectionStringSecretRef != nil {
		in, out := &in.ConnectionStringSecretRef, &out.ConnectionStringSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ReadBatchSize != nil {
		in, out := &in.ReadBatchSize, &out.ReadBatchSize
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLSourceSpec.
func (in *PostgreSQLSourceSpec) DeepCopy() *PostgreSQLSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveTransformation) DeepCopyInto(out *RemoveTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveTransformation.
func (in *RemoveTransformation) DeepCopy() *RemoveTransformation {
	if in == nil {
		return nil
	}
	out := new(RemoveTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaceFieldTransformation) DeepCopyInto(out *ReplaceFieldTransformation) {
	*out = *in
	if in.Renames != nil {
		in, out := &in.Renames, &out.Renames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaceFieldTransformation.
func (in *ReplaceFieldTransformation) DeepCopy() *ReplaceFieldTransformation {
	if in == nil {
		return nil
	}
	out := new(ReplaceFieldTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteRule) DeepCopyInto(out *RouteRule) {
	*out = *in
	in.Sink.DeepCopyInto(&out.Sink)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteRule.
func (in *RouteRule) DeepCopy() *RouteRule {
	if in == nil {
		return nil
	}
	out := new(RouteRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterTransformation) DeepCopyInto(out *RouterTransformation) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterTransformation.
func (in *RouterTransformation) DeepCopy() *RouterTransformation {
	if in == nil {
		return nil
	}
	out := new(RouterTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SASLConfig) DeepCopyInto(out *SASLConfig) {
	*out = *in
	if in.UsernameSecretRef != nil {
		in, out := &in.UsernameSecretRef, &out.UsernameSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SASLConfig.
func (in *SASLConfig) DeepCopy() *SASLConfig {
	if in == nil {
		return nil
	}
	out := new(SASLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchemaRegistryConfig) DeepCopyInto(out *SchemaRegistryConfig) {
	*out = *in
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.URLSecretRef != nil {
		in, out := &in.URLSecretRef, &out.URLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchemaRegistryConfig.
func (in *SchemaRegistryConfig) DeepCopy() *SchemaRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(SchemaRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectTransformation) DeepCopyInto(out *SelectTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectTransformation.
func (in *SelectTransformation) DeepCopy() *SelectTransformation {
	if in == nil {
		return nil
	}
	out := new(SelectTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SinkSpec) DeepCopyInto(out *SinkSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SinkSpec.
func (in *SinkSpec) DeepCopy() *SinkSpec {
	if in == nil {
		return nil
	}
	out := new(SinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnakeCaseTransformation) DeepCopyInto(out *SnakeCaseTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnakeCaseTransformation.
func (in *SnakeCaseTransformation) DeepCopy() *SnakeCaseTransformation {
	if in == nil {
		return nil
	}
	out := new(SnakeCaseTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSpec) DeepCopyInto(out *SourceSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSpec.
func (in *SourceSpec) DeepCopy() *SourceSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StructFlattenTransformation) DeepCopyInto(out *StructFlattenTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StructFlattenTransformation.
func (in *StructFlattenTransformation) DeepCopy() *StructFlattenTransformation {
	if in == nil {
		return nil
	}
	out := new(StructFlattenTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CertSecretRef != nil {
		in, out := &in.CertSecretRef, &out.CertSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.KeySecretRef != nil {
		in, out := &in.KeySecretRef, &out.KeySecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimestampTransformation) DeepCopyInto(out *TimestampTransformation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimestampTransformation.
func (in *TimestampTransformation) DeepCopy() *TimestampTransformation {
	if in == nil {
		return nil
	}
	out := new(TimestampTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimezoneTransformation) DeepCopyInto(out *TimezoneTransformation) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimezoneTransformation.
func (in *TimezoneTransformation) DeepCopy() *TimezoneTransformation {
	if in == nil {
		return nil
	}
	out := new(TimezoneTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformationSpec) DeepCopyInto(out *TransformationSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformationSpec.
func (in *TransformationSpec) DeepCopy() *TransformationSpec {
	if in == nil {
		return nil
	}
	out := new(TransformationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoSinkSpec) DeepCopyInto(out *TrinoSinkSpec) {
	*out = *in
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int32)
		**out = **in
	}
	if in.BatchFlushIntervalSeconds != nil {
		in, out := &in.BatchFlushIntervalSeconds, &out.BatchFlushIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.QueryTimeoutSeconds != nil {
		in, out := &in.QueryTimeoutSeconds, &out.QueryTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AutoCreateTable != nil {
		in, out := &in.AutoCreateTable, &out.AutoCreateTable
		*out = new(bool)
		**out = **in
	}
	if in.UpsertMode != nil {
		in, out := &in.UpsertMode, &out.UpsertMode
		*out = new(bool)
		**out = **in
	}
	if in.ConflictKey != nil {
		in, out := &in.ConflictKey, &out.ConflictKey
		*out = new(string)
		**out = **in
	}
	if in.RawMode != nil {
		in, out := &in.RawMode, &out.RawMode
		*out = new(bool)
		**out = **in
	}
	in.FlattenMetadataSpec.DeepCopyInto(&out.FlattenMetadataSpec)
	if in.Keycloak != nil {
		in, out := &in.Keycloak, &out.Keycloak
		*out = new(KeycloakConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerURLSecretRef != nil {
		in, out := &in.ServerURLSecretRef, &out.ServerURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.CatalogSecretRef != nil {
		in, out := &in.CatalogSecretRef, &out.CatalogSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SchemaSecretRef != nil {
		in, out := &in.SchemaSecretRef, &out.SchemaSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoSinkSpec.
func (in *TrinoSinkSpec) DeepCopy() *TrinoSinkSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoSinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoSourceSpec) DeepCopyInto(out *TrinoSourceSpec) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(int32)
		**out = **in
	}
	if in.Keycloak != nil {
		in, out := &in.Keycloak, &out.Keycloak
		*out = new(KeycloakConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ServerURLSecretRef != nil {
		in, out := &in.ServerURLSecretRef, &out.ServerURLSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.CatalogSecretRef != nil {
		in, out := &in.CatalogSecretRef, &out.CatalogSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.SchemaSecretRef != nil {
		in, out := &in.SchemaSecretRef, &out.SchemaSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.TableSecretRef != nil {
		in, out := &in.TableSecretRef, &out.TableSecretRef
		*out = new(SecretRef)
		**out = **in
	}
	if in.ReadBatchSize != nil {
		in, out := &in.ReadBatchSize, &out.ReadBatchSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoSourceSpec.
func (in *TrinoSourceSpec) DeepCopy() *TrinoSourceSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoSourceSpec)
	in.DeepCopyInto(out)
	return out
}
