version: '3'

vars:
  MCP_IMAGE:
    sh: echo "${MCP_IMAGE:-mcp-dataflow:latest}"
  REGISTRY: ghcr.io
  IMAGE_NAME: ilyario/mcp-dataflow
  VERSION:
    sh: echo "${VERSION:-latest}"
  BUILD_DIR: dist
  LOCALBIN:
    sh: echo "$(pwd)/bin"

tasks:
  default:
    desc: Build MCP DataFlow server binary
    deps: [fmt, vet]
    cmds:
      - go build -o mcp-dataflow cmd/server/main.go

  help:
    desc: Display this help
    cmds:
      - task --list

  # Development tasks
  fmt:
    desc: Run go fmt against code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet against code
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint (if available)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run ./...
        else
          echo "golangci-lint not found, skipping..."
        fi

  test:
    desc: Run all tests
    deps: [fmt, vet]
    cmds:
      - go test ./... -v

  test-coverage:
    desc: Run tests with coverage
    deps: [fmt, vet]
    cmds:
      - go test ./... -coverprofile cover.out -covermode=atomic
      - go tool cover -html=cover.out -o cover.html
      - echo "Coverage report generated: cover.html"

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  # Build tasks
  build:
    desc: Build binary for current platform
    deps: [fmt, vet]
    cmds:
      - go build -o mcp-dataflow cmd/server/main.go
      - echo "Build complete: ./mcp-dataflow"

  build-all:
    desc: Build binaries for all platforms
    deps: [fmt, vet]
    cmds:
      - chmod +x build.sh
      - ./build.sh {{.VERSION}}
      - echo "Build complete! Binaries are in {{.BUILD_DIR}}/"

  build-linux:
    desc: Build binary for Linux amd64
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o {{.BUILD_DIR}}/mcp-dataflow-linux-amd64 cmd/server/main.go

  build-darwin:
    desc: Build binary for macOS (Intel)
    cmds:
      - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -o {{.BUILD_DIR}}/mcp-dataflow-darwin-amd64 cmd/server/main.go

  build-darwin-arm:
    desc: Build binary for macOS (Apple Silicon)
    cmds:
      - CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -a -installsuffix cgo -o {{.BUILD_DIR}}/mcp-dataflow-darwin-arm64 cmd/server/main.go

  build-windows:
    desc: Build binary for Windows amd64
    cmds:
      - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -o {{.BUILD_DIR}}/mcp-dataflow-windows-amd64.exe cmd/server/main.go

  # Docker tasks
  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.MCP_IMAGE}} .
      - echo "Docker image built: {{.MCP_IMAGE}}"

  docker-build-registry:
    desc: Build Docker image tagged for registry
    cmds:
      - docker build -t {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}} .
      - docker tag {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}} {{.REGISTRY}}/{{.IMAGE_NAME}}:latest
      - echo "Docker image built: {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}"

  docker-run:
    desc: Run Docker container for testing
    cmds:
      - |
        docker run --rm -it \
          -v ${HOME}/.kube/config:/root/.kube/config:ro \
          {{.MCP_IMAGE}} \
          --kubeconfig /root/.kube/config

  docker-push:
    desc: Push Docker image to registry
    deps: [docker-build-registry]
    cmds:
      - docker push {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/{{.IMAGE_NAME}}:latest
      - echo "Docker image pushed to {{.REGISTRY}}/{{.IMAGE_NAME}}"

  # Release tasks
  release:
    desc: Create release (build all binaries and Docker image)
    deps: [build-all, docker-build-registry]
    cmds:
      - echo "Release build complete!"
      - echo "Binaries: {{.BUILD_DIR}}/"
      - echo "Docker image: {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}"

  # Cleanup tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f mcp-dataflow mcp-dataflow.exe
      - rm -rf {{.BUILD_DIR}}/
      - rm -f cover.out cover.html
      - echo "Clean complete"

  clean-all:
    desc: Clean all artifacts including Docker images
    deps: [clean]
    cmds:
      - docker rmi {{.MCP_IMAGE}} 2>/dev/null || true
      - docker rmi {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}} 2>/dev/null || true
      - docker rmi {{.REGISTRY}}/{{.IMAGE_NAME}}:latest 2>/dev/null || true
      - echo "Clean all complete"
